# Generated by Django 5.1.3 on 2024-12-30 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('SEK', 'Swedish Krona'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='SEK', max_length=10)),
                ('timezone', models.CharField(default='Europe/Stockholm', max_length=50)),
                ('notifications', models.BooleanField(default=True, help_text='Receive notifications via email')),
                ('light_mode', models.BooleanField(default=True, help_text='Toggle light/dark mode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
