# Generated by Django 5.1.4 on 2025-01-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
