# Generated by Django 5.1.4 on 2025-01-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_budgetaccess_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='slug',
            field=models.SlugField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
