# Generated by Django 5.1.4 on 2025-01-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_budget_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetaccess',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
